### ISSUE TITLE
Compliance around payments via ACH/Check

### ISSUE THREAD

**Issue by garyhtou** [hackclub/hcb#4902]
### Tasks
- [x] Collect invoices/receipts prior to payment
- [x] Collect receipts for all payments including ACHs/Checks
- [x] https://github.com/hackclub/hcb/issues/5348

---

- contractor (salary): w9 with invoice. w8-ben
  - How does this differ from card charges? We don't require W9 for that
- payment good & services: invoice
  - over $600 per calendar year (maybe we should just require it regardless of total sent per year)
- reimbursement: receipt
- grants: we don't need anything

**Comment by garyhtou** [comment]
I will setup a meeting with Liv and Bence to chat more about our requirements for this

**Comment by garyhtou** [comment]
https://github.com/hackclub/hcb/issues/4831 will handle a portion of this issue. The goal of this issue to provide more thoughts into payment compliance in general

**Comment by garyhtou** [comment]
Decisions from meeting with Bence on January 5th:

- We will collect a W-9/W-8 BEN for ALL payments
    - Regardless of if it's under $600
    - Reimbursements do NOT count in the $600; and thus do not need a W-9
- We need a reliable way to identify a single entity (counter party)
	- This is because two orgs may invoice the same person. The total of the two invoices is what we paid that person.
	- Email addresses are a great identifier, but it's not 100% reliable. A person may have multiple email addresses.
- We will require invoices/receipts BEFORE payment (except for card)
	- This applies to ACHs and Checks
- We need a receipt for EVERY payment
	- This includes every recurring payments (e.g. subscriptions)
	- This also includes reimbursements

## Open Questions
- How do we uniquely identify an individual?
	- Probably via their W-9 info (SSN)
- How do we securely store W-9/W8-BEN/SSN?

**Comment by garyhtou** [comment]
I'm continuing this conversation with Kris

https://hackclub.slack.com/archives/C04T8NL8TCJ/p1707140614320939

**Comment by Luke-Oldenburg** [comment]
Contractors / Payments feature
